/* constants/icons-3d.ts */
export const Icons3D = {
  ambulance2: require('@3d/ambulance2.png'),
  ticketAdd: require('@3d/+ticket.png'),
  bookmark: require('@3d/bookmark.png'),
  calendar: require('@3d/calender.png'), // o arquivo está como "calender.png" mesmo
  call: require('@3d/call.png'),
  cam: require('@3d/cam.png'),
  cashback: require('@3d/cashback.png'),
  champions: require('@3d/champions.png'),
  champions2: require('@3d/champions2.png'),
  chat: require('@3d/chat.png'),
  chat2: require('@3d/chat2.png'),
  check: require('@3d/check.png'),
  crown: require('@3d/crown.png'),
  docCheck: require('@3d/doc-check.png'),
  docCheck2: require('@3d/doc-check2.png'),
  docCheck3: require('@3d/doc-check3.png'),
  document: require('@3d/document.png'),
  document2: require('@3d/document2.png'),
  flame: require('@3d/flame.png'),
  flame2: require('@3d/flame2.png'),
  gift: require('@3d/gift.png'),
  gift2: require('@3d/gift2.png'),
  like: require('@3d/like.png'),
  like2: require('@3d/like2.png'),
  location: require('@3d/location.png'),
  map: require('@3d/map.png'),
  medical: require('@3d/medical.png'),
  notification: require('@3d/notification.png'),
  panic: require('@3d/panic.png'),
  payments: require('@3d/payments.png'),
  profile: require('@3d/perfil.png'),
  podium: require('@3d/podium.png'),
  policies: require('@3d/policies.png'),
  price: require('@3d/price.png'),
  price2: require('@3d/price2.png'),
  privacy: require('@3d/privacidade.png'),
  qrcode: require('@3d/qrcode.png'),
  qrcode2: require('@3d/qrcode2.png'),
  rating: require('@3d/rating.png'),
  rating2: require('@3d/rating2.png'),
  rating3: require('@3d/rating3.png'),
  security: require('@3d/security.png'),
  share: require('@3d/share.png'),
  stepProfile: require('@3d/step1-card-profile.png'),
  stepCalendar: require('@3d/step2-book-calendar.png'),
  support: require('@3d/support.png'),
  support2: require('@3d/support2.png'),
  ticket: require('@3d/ticket.png'),
  ticket3: require('@3d/ticket3.png'),
  tickets: require('@3d/tickets.png'),
  time: require('@3d/time.png'),
  time2: require('@3d/time2.png'),
  time3: require('@3d/time3.png'),
  uptrend: require('@3d/uptrend.png'),

  // ---- injetados ----
  shield: require('@3d/shield-safe.png'),
  trophyGold: require('@3d/trophy-gold.png'),
  medalGold: require('@3d/medal-gold-blue.png'),
  medalSilver: require('@3d/medal-silver-blue.png'),
  medalBronze: require('@3d/medal-bronze-blue.png'),
  phone911: require('@3d/phone911.png'),

  // ---- Adições solicitadas ----
  experience: require('@3d/experience.png'),
  facial: require('@3d/facial.png'),
  provider: require('@3d/provider.png'),
  woman: require('@3d/woman.png'),
  button: require('@3d/button.png'),
  wsupport: require('@3d/wsupport.png'),
} as const;

export type Icon3DName = keyof typeof Icons3D;