steps:
- name: 'gcr.io/cloud-builders/docker'
  # O comando `build` será executado no contexto da pasta 'backend-cleaning'.
  # O último argumento '.' refere-se ao `Dockerfile` dentro do diretório especificado pelo 'dir'.
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/limpeja-app-backend:latest', '.']
  # Esta linha 'dir' é CRUCIAL. Ela muda o diretório de trabalho antes de executar o 'docker build'.
  # Garante que o 'Dockerfile' e o 'package.json' do seu backend sejam encontrados.
  dir: 'backend-cleaning' # <- ESTA LINHA É A CORREÇÃO PRINCIPAL

images:
- 'gcr.io/${PROJECT_ID}/limpeja-app-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY # Isso resolve o erro de logging