// backend-cleaning/src/coupons/entities/coupon.entity.ts
// This file typically represents the structure of your database entity,
// often derived from Prisma models or defined for DTOs.

// For demonstration, these enums are defined here, but they should ideally come from prisma/schema.prisma
// and be imported from `@prisma/client` if using Prisma Client types.
export enum CouponType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
}

export enum CouponTarget {
  ALL = 'ALL',
  NEW_CLIENTS = 'NEW_CLIENTS',
  SPECIFIC_SERVICE = 'SPECIFIC_SERVICE',
  SPECIFIC_PROVIDER = 'SPECIFIC_PROVIDER',
}

export enum CouponStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  EXPIRED = 'EXPIRED',
  USED_UP = 'USED_UP', // When maxUses is reached
}

// This interface would typically be generated by Prisma Client or manually defined
// to match the `model Coupon` in `schema.prisma`.
export interface Coupon {
  id: string;
  code: string;
  type: CouponType;
  value: number; // Stored as Decimal in DB, number in TS
  validFrom: Date;
  validUntil: Date;
  maxUses?: number;
  usesCount: number;
  target: CouponTarget;
  targetId?: string;
  status: CouponStatus;
  createdAt: Date;
  updatedAt: Date;
  // transactions?: any[]; // Prisma relation to Transaction
}